replicaCount: 2

image:
  # Set via CI/Terraform or environment-specific values file.
  # Example: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/lesson-8-9-django
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "*"

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
