apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: {{ .Values.argocd_namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git_repo_url }}
    targetRevision: main
    path: final-project/charts/django-app
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.app_namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
